version: '3.5'

services:

  mongo:
    image: "mongo"
    restart: unless-stopped
    volumes:
      - mongodb-server-linux-data:/data/db
    ports:
      - target: 27017
        published: 27017

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/robin/.docker/config.json:/config.json
    command: --interval 30

  mssql:
    image: "mcmoe/mssqldocker"
    restart: unless-stopped
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - target: 1433
        published: 1433
    environment:
      MSSQL_DB: "padel"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Express"

  gateway:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/gateway"
    restart: unless-stopped
    environment:
      CHAT_ADDRESS: "social:5001"
      IDENTITY_ADDRESS: "identity:5002"
      NOTIFICATION_ADDRESS: "notification:5003"
    ports:
      - target: 50051
        published: 50051

  social:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/social"
    restart: unless-stopped
    environment:
      CHAT_Connections__MongoDb__padel__url: "mongodb://mongo:27017"
      CHAT_Connections__MongoDb__padel__database: "padel"
      CHAT_AWS__AccessKey: "AKIARZV2LEFOZ6LF2IPW"
      CHAT_AWS__SecretKey: "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"
      CHAT_AWS__Region: "eu-north-1"
      CHAT_AWS__Queue__Name: "chat-service"
      CHAT_AWS__ProfileBucket: "mkdir.se.padpals.profile-pictures"

  identity:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/identity"
    restart: unless-stopped
    environment:
      IDENTITY_Connections__Sql__padel: "Server=mssql,1433;Database=padel;User=sa;Password=yourStrong(!)Password;"
      IDENTITY_AWS__AccessKey: "AKIARZV2LEFOZ6LF2IPW"
      IDENTITY_AWS__SecretKey: "XRlwiULA747KLVutN/lF+mRMYPvMUmcHffR3EfIl"
      IDENTITY_AWS__Region: "eu-north-1"
      IDENTITY_AWS__Queue__Name: "identity-service"

  notification:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/notification"
    restart: unless-stopped
    volumes:
      - "/home/robin/Downloads/padpal-firebase-adminsdk.json:/config/padpal-firebase-adminsdk.json:"
    environment:
      NOTIFICATION_Connections__MongoDb__padel__url: "mongodb://mongo:27017"
      NOTIFICATION_Connections__MongoDb__padel__database: "padel"
      NOTIFICATION_AWS__AccessKey: "AKIARZV2LEFOZ6LF2IPW"
      NOTIFICATION_AWS__SecretKey: "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"
      NOTIFICATION_AWS__Region: "eu-north-1"
      NOTIFICATION_AWS__Queue__Name: "notification-service"
      NOTIFICATION_AWS__Topics__0: "social_v1_ChatMessageReceived"
      NOTIFICATION_AWS__Topics__1: "social_v1_FriendRequestAccepted"
      NOTIFICATION_AWS__Topics__2: "social_v1_FriendRequestReceived"
      NOTIFICATION_AWS__Topics__3: "game_v1_GameCreated"
      GOOGLE_APPLICATION_CREDENTIALS: "/config/padpal-firebase-adminsdk.json"

volumes:
  mssql-server-linux-data:
  mongodb-server-linux-data:

