version: '3.5'

services:

  gateway:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/gateway"
    environment:
      CHAT_ADDRESS: "chat:5001"
      IDENTITY_ADDRESS: "identity:5002"
      NOTIFICATION_ADDRESS: "notification:5003"
    ports:
      - target: 50051
        published: 50051

  chat:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/chat"

  identity:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/identity"

  notification:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/notification"

