version: '3.5'

services:

  gateway:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/gateway"
    environment:
      CHAT_ADDRESS: "chat:5001"
    ports:
      - target: 50051
        published: 50051

  chat:
    image: "docker.pkg.github.com/mkdir-sweden/padpal/chat"
    environment:
      GODEBUG: "${GODEBUG_ENV}"

