name: user_repository
description: A new Flutter package.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  equatable: ^1.2.0
  meta: ^1.1.8
  uuid: ^2.1.0

#dev_dependencies:
